"""unique constraints on targets.base_url and tasks(target_id, task_type)

Revision ID: 44b3551330e1
Revises: 961c6aad09c4
Create Date: 2026-09-04 19:45:47.169510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44b3551330e1'
down_revision: Union[str, None] = '961c6aad09c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_targets_base_url'), ['base_url'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tasks_target_id_task_type', ['target_id', 'task_type'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tasks_target_id_task_type', type_='unique')

    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_targets_base_url'), type_='unique')

    # ### end Alembic commands ###
